version: '3'

services:
   frontend:
     build: .
     image: front
     ports:
       - 5000:5000
     depends_on:
       - backend

   backend:
     build: .
     image: back
     environment:
      - 'REDIS=redis'
      - 'DB_HOST=postgres'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=mysecretpassword'
     ports:
      - 8000:8000
     depends_on:
      - redis
      - postgres

   redis:
     image: redis
     volumes:
      - ./redis-data:/data

   postgres:
     image: postgres
     environment:
      - 'POSTGRES_PASSWORD=mysecretpassword123'
     volumes:
      - ./pgdata:/var/lib/postgresql/data

   proxy:
     image: jwilder/nginx-proxy
     volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
     ports:
      - 80:80
     depends_on:
      - frontend
      - backend
