version: '3'

services:
   frontend:
     build: .
     image: front
     ports:
       - 5000:5000
   backend:
     build: .
     image: back
     environment:
      - 'REDIS=redis'
      - 'DB_HOST=postgres'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=mysecretpassword'
     ports:
      - 8000:8000
     depends_on:
      - redis
      - postgres   
   redis:
     image: redis
   
   postgres:
     image: postgres
     environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
